# Generated by Django 3.0.1 on 2021-01-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostdb',
            name='date',
            field=models.DateField(),
        ),
    ]
